GET http://localhost:3000/customers

###
GET  http://localhost:3000/customers/1

###
PUT http://localhost:3000/customers/2
Content-Type: application/json

{
    "username": "cliente2",
    "address": "Calle 8",
    "phone_num": "9879797979",
    "pay_method": "Efectivo"
}
###
DELETE http://localhost:3000/customers/2
###
